alchemy-json_api.gemspec, app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/node_serializer.rb, lib/alchemy/json_api/version.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb, spec/serializers/alchemy/json_api/language_serializer_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
This fixes the test suite to work with recent versions of Alchemy and bumps the version to 0.2.0.
=> Fix specs, bump version

app/controllers/alchemy/json_api/pages_controller.rb, config/routes.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb, spec/routing/layout_page_routing_spec.rb, spec/routing/page_routing_spec.rb
We are able to request nested urlnames now as well. Before we only support top level urlnames.
=> Add support for nested urlnames

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/essence_boolean_serializer.rb, app/serializers/alchemy/json_api/essence_date_serializer.rb, app/serializers/alchemy/json_api/essence_file_serializer.rb, app/serializers/alchemy/json_api/essence_html_serializer.rb, app/serializers/alchemy/json_api/essence_link_serializer.rb, app/serializers/alchemy/json_api/essence_node_serializer.rb, app/serializers/alchemy/json_api/essence_page_serializer.rb, app/serializers/alchemy/json_api/essence_picture_serializer.rb, app/serializers/alchemy/json_api/essence_richtext_serializer.rb, app/serializers/alchemy/json_api/essence_select_serializer.rb, app/serializers/alchemy/json_api/essence_text_serializer.rb
Ruby is very picky with constants and Rails auto loading is doing the rest. So we need to make sure to not intropuce two constants in this Gem.
=> Use full module paths in serializers

app/controllers/alchemy/json_api/base_controller.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
We need the error messages during development
=> Only include errors mixin in production mode

app/serializers/alchemy/json_api/element_serializer.rb, spec/serializers/alchemy/json_api/element_serializer_spec.rb
This is the name of the attribute in Alchemy core, so we should use that name as well.
=> Rename element_type into name

app/controllers/alchemy/json_api/base_controller.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
This reverts commit e2d71b10d7a53da3a3c4f634a418cadf8d6e092c.
Das war eine doofe Idee
=> Revert "Only include errors mixin in production mode"

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/essence_node_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb
If we don't do this, we run into a bug in production where this gem will
try to load Alchemy's internal serializers (`Alchemy::NodeSerializer`
and friends).
=> Specify Record Type and Serializer Class for all relations

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/essence_node_serializer.rb, app/serializers/alchemy/json_api/essence_page_serializer.rb, app/serializers/alchemy/json_api/language_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, lib/alchemy/json_api/essence_serializer.rb
There are naming conflicts with core Alchemy serializers that need to be
resolved cleanly. This does that.
=> Fully qualify the names of Serializer classes

app/controllers/alchemy/json_api/pages_controller.rb
CanCanCan is not able to merge the `accessible_by` scope with other scopes.
=> Fix page base scope for anonymous users

alchemy-json_api.gemspec, app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/language_serializer.rb, app/serializers/alchemy/json_api/node_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, lib/alchemy/json_api/essence_serializer.rb
Use the maintained fork of the [unmaintained](https://github.com/Netflix/fast_jsonapi#fast-json-api--warning-this-project-is-no-longer-maintained-warning) `fast_jsonapi` gem.
This is breaking of you have custom serializers that use the `FastJsonApi::ObjectSerializer`.
Closes #22
=> Switch from fast_jsonapi to jsonapi-serializer

app/controllers/alchemy/json_api/layout_pages_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb, spec/dummy/config/initializers/devise.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb
Layoutpages do not have publication dates since they are not routable and are always displayed in the context of another page.
=> Return all layoutpages regardless of publication status

Gemfile, app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/dummy/config/alchemy/elements.yml, spec/requests/alchemy/json_api/pages_spec.rb
Like with non-public and trashed elements we do not want to include deprecated elements (a new feature in Alchemy 5.2) with the public API responses.
=> Do not include deprecated elements and essences

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/serializers/alchemy/json_api/element_serializer_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
We need to remove the deprecated elements from all relations since
they are not included in the all_elements relation anymore.
=> Remove deprecated elements from all element relations

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/dummy/config/alchemy/elements.yml, spec/requests/alchemy/json_api/pages_spec.rb, spec/serializers/alchemy/json_api/element_serializer_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
This reverts #26 and #28
We agreed on keeping the deprecated elements in the response and add the attribute to the serializer (upcoming PR) instead. The frontend should decide what to do with deprecated elements and contents.
=> Revert removal of deprecated elements

app/serializers/alchemy/json_api/element_serializer.rb, lib/alchemy/json_api/essence_serializer.rb, lib/alchemy/json_api/test_support/essence_serializer_behaviour.rb, spec/dummy/config/alchemy/elements.yml, spec/serializers/alchemy/json_api/element_serializer_spec.rb
Adds the `deprecated` attribute to elements and essence serializers. This attribute has been introduced in Alchemy 5.2
=> Add deprecated attribute to elements and contents

app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/language_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/serializers/alchemy/json_api/element_serializer_spec.rb, spec/serializers/alchemy/json_api/language_serializer_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
We currently building the public frontend API with this and try to make
this fast and feature parity as a replacement to the legacy JSON api from
Alchemy core.
Therefore we want to concentrate on the frontend attributes now and remove
currently not even supported admin flag.
=> Remove admin features from serializers

alchemy-json_api.gemspec, app/controllers/alchemy/json_api/pages_controller.rb, app/models/alchemy/json_api/element.rb, app/models/alchemy/json_api/page.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/models/alchemy/json_api/element_spec.rb, spec/models/alchemy/json_api/page_spec.rb, spec/rails_helper.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
This optimizes loading of elements by introducing decidated models that uses ruby methods to filter elements by attributes instead of using the database. This allows to preload `all_elements` at once and reduces DB queries a lot.
co-authored by @mamhoff
=> Optimize elements loading

lib/alchemy/json_api/test_support/essence_serializer_behaviour.rb
This only works with this dummy app and its `elements.yml` if we do not also stub the content definition.
=> Fix essence serializer RSpec behavior

.gitignore, app/models/alchemy/json_api/element.rb
The `Alchemy::Element::ElementContents` mixin can call `Alchemy::Logger#log_warning` if content definitions are missing. The `Alchemy::Logger` module needs to be included in `Alchemy::JsonApi::Element`, otherwise we get a method missing error for `#log_warning` instead of actually logging a warning.
Fixes this:
```
NoMethodError (undefined method `log_warning' for #<Alchemy::JsonApi::Element:0x00007fefd9dfe5a0>):
/Users/pelargir/.rvm/gems/ruby-2.7.2@cs_spree_3_0/gems/activemodel-6.0.3.4/lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/pelargir/.rvm/gems/ruby-2.7.2@cs_spree_3_0/bundler/gems/alchemy_cms-efd7feab0462/app/models/alchemy/element/element_contents.rb:103:in `content_definition_for'
/Users/pelargir/.rvm/gems/ruby-2.7.2@cs_spree_3_0/bundler/gems/alchemy_cms-efd7 …
```
=> Add missing Alchemy::Logger include to Element

.github/workflows/ci.yml, spec/models/alchemy/json_api/element_spec.rb, spec/models/alchemy/json_api/page_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
Alchemy 6 removes this feature and in old versions it is deprecated
=> Remove tests for trashed elements

app/models/alchemy/json_api/page.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/models/alchemy/json_api/page_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
This adds legacy URLs to the page serializer. Since legacy URLs only have one useful field (`urlname`) I opted to include these as an attribute on the page instead of creating an extra serializer for legacy URLs.
=> Add legacy URLs to page serializer

app/controllers/alchemy/json_api/pages_controller.rb
This eliminates an N+1 query in the pages controller by preloading legacy page URLs.
=> Preload legacy page URLs

app/controllers/alchemy/json_api/admin/layout_pages_controller.rb, app/controllers/alchemy/json_api/admin/pages_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb
Fixes admin controllers so that the correct page version is used (we always want the draft version in admin controllers).
=> Admin controller fixes

app/serializers/alchemy/json_api/essence_richtext_serializer.rb, spec/serializers/alchemy/json_api/essence_richtext_serializer_spec.rb
This adds the new `sanitized_body` column from Alchemy 6 to the JSONAPI output.
=> Serialize the new sanitized_body column from Alchemy

app/controllers/alchemy/json_api/pages_controller.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
When accessing an unpublished page as an admin, the previous code would
result in the API returning a 200 response and a page with no elements.
It is more correct to return a 404. By joining the pages to their
version, we make sure this happens.
=> Join to page version in PagesController

app/controllers/alchemy/json_api/admin/pages_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb, app/models/alchemy/json_api/page.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/models/alchemy/json_api/page_spec.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
Useful if you want to serialize the page categorizations in a breadcrumb for instance.
=> Add ancestors relationship to page serializer

app/controllers/alchemy/json_api/admin/layout_pages_controller.rb, app/controllers/alchemy/json_api/admin/pages_controller.rb, app/controllers/alchemy/json_api/layout_pages_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb, app/serializers/alchemy/json_api/element_serializer.rb, app/serializers/alchemy/json_api/page_serializer.rb, spec/controllers/alchemy/json_api/admin/pages_controller_spec.rb, spec/requests/alchemy/json_api/admin/layout_pages_spec.rb, spec/requests/alchemy/json_api/admin/pages_spec.rb, spec/requests/alchemy/json_api/layout_pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
1. Caches the serialization result
Uses the jsonapi-serializer feature for caching that uses the configured Rails cache store.
Never expire the records because page and element records have a cache_key that is updated by alchemy in the correct way.
2. Adds HTTP caching
Uses [conditional get](https://api.rubyonrails.org/v6.1.3.1/classes/ActionController/ConditionalGet.html#method-i-stale-3F) for loading page(s) only when necessary from the database. If the browser cache is still fresh we return a 304 instead.
=> Add caching

app/serializers/alchemy/json_api/essence_picture_serializer.rb, app/serializers/alchemy/json_api/ingredient_picture_serializer.rb, spec/serializers/alchemy/json_api/essence_picture_serializer_spec.rb, spec/serializers/alchemy/json_api/ingredient_picture_serializer_spec.rb
`srcset` is a powerful tool for providing responsive images. Alchemy has support for it on the HTML side of things for a very long time. Let's get this into the JAMStack age.
If `srcset` is defined on the element definition, then it returns an array of image candidates its descriptor and the image dimensions.
eg:
```json
{
"url": "cute-kittins.jpg",
"desc": "200w",
"width": "200",
"height": "100",
}
```
You can define `srcset` candidates either as a size `String` or a `Hash` supporting **all image transformations** Alchemy supports. So you are able to create cropped JPGs from a PNG for instance by doing this:
```yml
- name: Hero
contents:
- name: image
type: EssencePicture
settings:
size: 1920x700
srcset:
- size: 200x200
crop: true
quality: 60
format: jpg
- 860x350
```
=> Add srcset support

app/controllers/alchemy/json_api/pages_controller.rb, spec/rails_helper.rb, spec/requests/alchemy/json_api/admin/layout_pages_spec.rb, spec/requests/alchemy/json_api/admin/pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
A page can have caching disabled via the `cache: false` flag on a pages `page_layout` definition.
=> Add support for disabled cache per page

app/serializers/alchemy/json_api/essence_picture_serializer.rb, app/serializers/alchemy/json_api/ingredient_picture_serializer.rb, spec/serializers/alchemy/json_api/essence_picture_serializer_spec.rb, spec/serializers/alchemy/json_api/ingredient_picture_serializer_spec.rb
If you want to pass the image type to a `<picture>` `<source>` element you need to set the type as well.
=> Return image mime type with srcset responses

spec/dummy/config/application.rb, spec/dummy/config/initializers/session_store.rb
Alchemy requires a session store. Rails 7 now raises an error if
an app has no session store configured. Removes the api_only
from the dummy app, so it loads the session.
=> Add a session store to dummy app

app/controllers/alchemy/json_api/pages_controller.rb, app/models/alchemy/json_api/page.rb, spec/requests/alchemy/json_api/pages_spec.rb
We overwrote `ransackable_attributes` to only include `page_layout` and `urlname`, 
but Alchemy needs `name` as well. 
Fixed by adding `page_layout` to already defined `ransackable_attributes`.
=> Fix page search

Rakefile, alchemy-json_api.gemspec
In 2022, they released a new version of jsonapi.rb. The functionality almost did not change at all, so no changes on our side are necessary.
=> Allow jsonapi.rb 2.x

app/controllers/alchemy/json_api/pages_controller.rb, spec/requests/alchemy/json_api/pages_spec.rb
The `cache_key` is just the page id. We need to include the `cache_version` (the page `published_at` date).
=> fix(HTTP Cache): Use cache_key_with_version for etag

app/controllers/alchemy/json_api/nodes_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb
Hours is not fine enough as granularity for good cache control. For this reason, the `Cache-Control` header operates with a granularity of seconds as well. Let's also work with seconds here.
This is literally a breaking change, but it will only break caches.
=> Do not convert cache duration to hours

app/controllers/alchemy/json_api/admin/pages_controller.rb, app/controllers/alchemy/json_api/pages_controller.rb, spec/requests/alchemy/json_api/admin/layout_pages_spec.rb, spec/requests/alchemy/json_api/admin/pages_spec.rb, spec/requests/alchemy/json_api/pages_spec.rb
The Last-Modified header is a weaker cache key than the etag, and thus
we rely solely on the etag from now on. Browsers and Rails will ignore
it if it's not set while validating if a request is fresh.
=> Improve etag generation

app/serializers/alchemy/json_api/page_serializer.rb, spec/serializers/alchemy/json_api/page_serializer_spec.rb
This page value is not currently included. Adding it will allow consumers of the api to restrict pages.
=> Add restricted value to page serializer

.github/workflows/ci.yml, lib/alchemy/json_api/ingredient_serializer.rb, lib/alchemy/json_api/test_support/ingredient_serializer_behaviour.rb
This association causes infinite recursion during
deserialization, because the element is already
included in the page's elements association's data.
=> Remove element from IngredientSerializer

alchemy-json_api.gemspec
Allows jsonapi.rb to upgrade to 2.1.1. In this version they introduce code to the error serializer. This would be useful to be more semantic about errors.
Changes between versions:
https://my.diffend.io/gems/jsonapi.rb/2.0.1/2.1.1
=> Allow jsonapi.rb v2.1

.github/workflows/lint.yml, app/controllers/alchemy/json_api/base_controller.rb, dist/alchemy-json_api.js, dist/alchemy-json_api.mjs, dist/deserialize.mjs, package.json, rollup.config.js
Use these to use `import` over `require`.
=> Build .mjs (ES Modules) as well

README.md, app/controllers/alchemy/json_api/pages_controller.rb, spec/requests/alchemy/json_api/pages_spec.rb
In order to get efficient CDN (Edge) caching for your json api we allow to set the `stale-while-revalidate` header to any integer value in seconds via the `ALCHEMY_JSON_API_CACHE_STALE_WHILE_REVALIDATE` env variable. 
Also lowering the default cache duration (`max-age`) from 3 hours (`10800`s) to 10 minutes (`600`s). Since the browser will first revalidate after this time passed we ensure that newly published content is available sooner (3 hours is a long time for your marketing team to wait for new content to be visible to your visitors). Since the server will always validate against
the etag we send as cache key it will return 304 (not modified) in most cases.
=> Efficient edge caching

README.md, app/controllers/alchemy/json_api/pages_controller.rb, lib/alchemy/json_api.rb, spec/requests/alchemy/json_api/pages_spec.rb
Instead of ENV Vars we add support to set the caching options and `max-age` via the `Alchemy::JsonApi` Ruby API.
It falls back to the former ENV vars and we encourage to still use ENV vars to configure your API server, but you can just use Ruby integers if you like.
```rb
Alchemy::JsonApi.page_cache_max_age = ENV.fetch("ALCHEMY_JSON_API_CACHE_DURATION", 600).to_i
Alchemy::JsonApi.page_caching_options = {
stale_while_revalidate: ENV.fetch("ALCHEMY_JSON_API_CACHE_STALE_WHILE_REVALIDATE", 60).to_i
}
```
=> Use Ruby config to set caching options
